version: '3.8'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: landersonalmeida/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: landersonalmeida/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - 8080:80

networks:
  laranet:
    driver: bridge